### DISCUSSION TITLE
Is it possible to add Window Title Restrictions via the configuration file

### DISCUSSION THREAD

**Discussion by thesobercoder** [ianyh/Amethyst#1484] [Q&A] [answered]
I have written a custom configuration file that I use to float some applications; however, I'm unable to figure out how to add `Window Title Restrictions` for Finder windows like `Info`, `Copy`, etc. Is this currently possible?

Here is my `.amethyst.yml` file - 

```yaml
# Enable layouts
layouts:
  - tall
  - wide
  - two-pane
  - middle-wide
  - uniform-columns

# Disable mouse follows focus and focus follows mouse
mouse-follows-focus: false
focus-follows-mouse: false

# Enable window drag swapping
mouse-swaps-windows: true

# Float windows smaller than 500px
float-small-windows: true

# Disable mouse resizes window
mouse-resizes-windows: false

# Display the name of the layout when a new layout is selected
enables-layout-hud: true

# Display the name of the layout when moving to a new space
enables-layout-hud-on-space-change: true

# Restores window on launch
restore-layouts-on-launch: true

# Disable window margins
window-margins: false

# Enable floating for certain applications
floating-is-blacklist: true
floating:
  - com.apple.systempreferences
  - com.apple.ActivityMonitor
  - come.apple.calculator
  - com.apple.iCal
  - com.apple.mail
  - com.apple.MobileSMS
  - com.apple.Photos
  - com.apple.TV
  - com.apple.Music
  - com.apple.reminders
  - com.apple.Notes
  - com.apple.weather
  - com.apple.clock
  - com.apple.finder # I want to add title restrictions for this application only
```

**Comment by pschmidt88** [comment, marked as answer]
Yes.

Here is an example that I use to float the settings windows of IntelliJ:

```yaml
floating:
  - id: "com.jetbrains.intellij"
    window-titles:
      - "Settings"
```
