### DISCUSSION TITLE
How do I set floating rule for app that doesn't have bundle ID?

### DISCUSSION THREAD

**Discussion by smartding** [ianyh/Amethyst#1710] [Q&A]
I installed mpv(a video player launched through command line) through brew. mpv isn't a cask, I can't get its bundle ID with command as follows:
```bash
mdls -name kMDItemCFBundleIdentifier /Applications/mpv.app
```
So how do I set floating rule in amethyst that requires a bundle ID?

**Comment by ianyh** [comment]
As a workaround, it looks like mpv windows have `- mpv` at the end, so you could do a global floating window title rule with that suffix.

**Reply by smartding** [reply]
Would you be more specific? I use a yaml configuration file, but can't find guide about how to write floating rules. 

I tried something as below, but it doesn't work in 0.22.2 and macOS 15.3:

```yaml
floating:
- "com.apple.systempreferences"
- "com.apple.finder"
- id: "*"
  window-titles:
  - "*- mpv*"
```
