### ISSUE TITLE
needs a way to add window titles to yaml floating bundles list

### ISSUE THREAD

**Issue by caarlos0** [ianyh/Amethyst#1295]
**Is your feature request related to a problem? Please describe.**

I can configure Amethyst with YAML (which is awesome BTW), but can't set the window titles to float in the `floating` session.

**Describe the solution you'd like**

would be great to be able to do something like:

```yaml
floating:
- com.apple.mail
  windows:
  - 'foo' 
```

or

```yaml
floating:
- id: com.apple.mail
  windows:
  - 'foo' 
```

**Describe alternatives you've considered**

Not using yaml as config :( 

**Additional context**

n/a
