### ISSUE TITLE
Remove shortcut using config file

### ISSUE THREAD

**Issue by vicecaycedo** [ianyh/Amethyst#1329]
Is there a way to remove a shortcut (the default shortcuts) using the config yaml file?

**Comment by ianyh** [comment]
No, but it wouldn't be that hard to add. Just take something like `false` as meaning to unset a shortcut. Would be a good starter issue.

**Comment by agoodshort** [comment]
Related to this issue, if I set only the below in my config file, start a fresh install of Amethyst (e.g. `rm ~/Library/Preferences/com.amethyst.Amethyst.plist`).

When reviewing the preferences and shortcuts, I have now "mod1 + D" assigned to "Select fullscreen layout" and "Move focus clockwise".
When using Amethyst without a config file, it is not possible to set the same shortcut to 2 different commands, the UI does not allow it.

```yml
mod1:
    - option
    - shift

focus-cw:
    mod: mod1
    key: d
```

**Comment by mickimnet** [comment]
I only use a handful of functions with shortcuts, and was also trying to use the YAML config file.

Besides currently not being able to remove shortcuts with the YAML config file, removing them in the UI configuration section didn't help because after restarting _Amethyst_, they all reappeared again 🥺

**Comment by benjaminbauer** [comment]
@mickimnet using a config file will override the settings made in the UI. That is intended. The only way currently to remove shortcuts when using a config file is not to remove the declaration in the config but to set the unwanted shortcuts to a key combination that you don't use.

**Comment by vicmunoz** [comment]
> @mickimnet The only way currently to remove shortcuts when using a config file is not to remove the declaration in the config but to set the unwanted shortcuts to a key combination that you don't use.

Thanks for the workaround. I assume this is a bug, due currently (without config file) you can remove shortcuts safely.

**Comment by cowboy-bebug** [comment]
@vicecaycedo I'm on the latest [v0.20.0](https://github.com/ianyh/Amethyst/releases/tag/v0.20.0) and something like this works:
```yaml
focus-screen-1:
  mod: ""
  key: ""
```

**Comment by max-sixty** [comment]
FWIW having them empty for me doesn't work; so I have this to override the ones I don't use to a single shortcut I won't need:

```yaml
# Adding some random shortcuts so it doesn't put it default ones in
# https://github.com/ianyh/Amethyst/issues/1329
display-current-layout:
  mod: mod2
  key: x
cycle-layout:
  mod: mod2
  key: x
cycle-layout-backward:
  mod: mod2
  key: x
select-tall-layout:
  mod: mod2
  key: x
select-column-layout:
  mod: mod2
  key: x
select-wide-layout:
  mod: mod2
  key: x
toggle-tiling:
  mod: mod2
  key: x
reevaluate-windows:
  mod: mod2
  key: x
focus_main:
  mod: mod2
  key: x

```
