### ISSUE TITLE
Defaults Collision with Custom Config  

### ISSUE THREAD

**Issue by Indyandie** [ianyh/Amethyst#1419]
If a command (`mod`+`key`) is set in [**default.amethyst**](https://github.com/ianyh/Amethyst/blob/bfae0c3e769313fec1e4e0cc249b27e5e1d5fe75/Amethyst/default.amethyst) and the same command is reused in a [custom configuration file](https://github.com/ianyh/Amethyst/blob/bfae0c3e769313fec1e4e0cc249b27e5e1d5fe75/docs/configuration-files.md) neither will work. 

**To Reproduce**
1. create a custom config file at `~/.config/amethyst/amethyst.yml`
2. Add this to your file
    ```yml
    select-two-pane-layout:
      mod: mod1
      key: s
    ```
3. Relaunch Amethyst
4. press `mod1`+`s`
5. Nothing happens...

**Expected behavior**
The custom configuration command should override the default without issues. 

**Versions:**
 - macOS: 12.6.3
 - Amethyst: 0.17.0
 
**Additional context**
Initial discussion #1384

**Comment by vicmunoz** [comment]
In fact, all defaults are recreated on each relaunch if using custom configuration file `~/.amethyst.yml`
To Repoduce:
1. Set any custom configuration file without cycle-layout setting key
2. Remove shortcut for cycle-layout via in-app preferences
3. Relaunch amethyst
4. Check shortcuts via in-app preferences and voilá, the shortcut for cycle-layout is set again to its default.

Expected behavior
updated shortcuts via in-app preferences should not be reseted to defaults on each relaunch

Versions:
* macos 12.5.1
* amthyst 0.19.0 (103)

final notes: this issue is not reproduced if there is no custom configuration file. shortcuts remains as unset after relaunch, despite has its default 

maybe related with #1329

**Comment by roeeyn** [comment]
Adding my 2 cents, I was struggling because I was trying to configure the `3Column Middle` layout to work with `mod1+s` and thought it was related to this issue. Setting this (as the [docs suggest](https://github.com/ianyh/Amethyst/blob/development/docs/configuration-files.md#layout-selection)) didn't work:

```yaml
select-3column-middle-layout:
  mod: mod1
  key: s
```

But here, the issue is different. The root cause for this is that the layout is named '3Column Middle', but it has configured `middle-wide` as `layoutKey` as seen [here](https://github.com/ianyh/Amethyst/blob/265f6c8a75b84c0082549dd2577989ba6a436bbb/Amethyst/Layout/Layouts/ThreeColumnLayout.swift#L265-L266).

Based on this, configuring the following snippet worked well:
```yaml
# The default select-wide-layout keybinding is mod1+s, so I need to reassign
# it to another one, so I can later use the original.
select-wide-layout:
  mod: mod2
  key: x

# Assign the desired keybinding to the middle-layout.
# Make sure you have middle-wide in your layout list.
select-middle-wide-layout:
  mod: mod1
  key: s
```

I'm happy to add more details about this in the README if needed because there's info saying that "3Column Middle" was previously named "Middle Wide", but didn't find something saying that we should configure it that way in our configuration file.

**Comment by Indyandie** [comment]
Thanks @roeeyn your solution helped me find a work around for my original issue. 

By giving `select-wide-layout` a new shortcut, the default shortcut becomes available.

```yml
select-wide-layout:
  mod: mod1
  key: "0"

select-two-pane-layout:
  mod: mod1
  key: "s"

```

**Comment by ickc** [comment]
I am probably experiencing a similar bug but mine isn't the same of the defaults, specifically, this is my file,

[amethyst.yml.txt](https://github.com/ianyh/Amethyst/files/14002534/amethyst.yml.txt)

To ensure the problem isn't stateful, `defaults delete com.amethyst.Amethyst.plist` is run and the following behavior would still occur:

Namely, I mapped `mod1` + `a,s,d,f` to `Select fullscreen layout, Select bsp layout, Select wide layout, Select floating layout` respectively, and only the `mod1` + `s,d` work but `mod1` + `a,f` doesn't. The default of the latter is mapping to `Select tall layout, Select column layout` so it isn't the same as defaults (and in fact I didn't enable tall nor column in my `layouts` key.)

Even more strangely, at one point this (config file) actually works for `mod1` + `a,s,d,f`, but it has other problems. Restarting Amethyst didn't help (`mod2` + `z` wasn't even registered) and that's when I ran `defaults delete com.amethyst.Amethyst.plist` and after that I consistently see the above behavior.

Edit: probably unrelated to this issue. See https://github.com/ianyh/Amethyst/issues/1419#issuecomment-1902810820 for fixes in this particular case.

**Comment by cowboy-bebug** [comment]
FYI, you can unset default values like:
```yaml
focus-screen-1:
  mod: ""
  key: ""
```

@Indyandie using the above can you try:
```yaml
select-wide-layout:
  mod: ""
  key: ""

select-two-pane-layout:
  mod: mod1
  key: s
```

**Comment by ickc** [comment]
Perhaps that was replying to me?

Thanks. That works. Perhaps it is unrelated to this issue. Sorry for the noise.

**Comment by Indyandie** [comment]
it worked for me. Thanks for the hint @cowboy-bebug!

**Comment by cowboy-bebug** [comment]
Hey @Indyandie, can this issue be resolved? 🙏

You can unset default keys like this: https://github.com/cowboy-bebug/dotfiles/commit/39eb3d782a1fadc38660061dea98d70228731b8d

```yaml
focus-screen-1:
  mod: mod1     # this has to be a valid value (so `mod1-mod4`)
  key: <unset>  # this can be set any value
```
