### ISSUE TITLE
Float little arc windows?

### ISSUE THREAD

**Issue by ytubs** [ianyh/Amethyst#1509]
**Is your feature request related to a problem? Please describe.**
Feature Request

**Describe the solution you'd like**
Possibly it is not possible without a change in Arc's application packaging/bundling, but I'd like to be able to float only "Little arc" windows, with floating the browser's regular/main windows

**Comment by mpeterson** [comment]
it would be nice to have a way to use the identifier (`littleBrowserWindow-*`) as a filter, and not just the window title

<img width="1044" alt="image" src="https://github.com/ianyh/Amethyst/assets/11870/48726bd8-729a-4bc7-a6a2-8bbf31467def">

**Comment by rutger1140** [comment]
This is something I'm looking for as well. I like the 'Little Arc' feature, but it pushes my windows all over the place.
Perhaps we could extend on the work of #981 #1166? (I'm not very proficient in Swift though)

**Comment by rutger1140** [comment]
There does seem to be some window title prefix, but I'm not sure how to target it with regex. I've tried:

`/^(?!Little Arc).*/` and `/^(Little Arc).*/` while my floating is set to 'Automatically float all applications except those listed.'. Without success.

![Scherm­afbeelding 2023-10-26 om 09 37 06](https://github.com/ianyh/Amethyst/assets/357924/a49759eb-08c6-45dc-918a-ce0265df6bd5)

**Comment by diegoquinteiro** [comment]
@rutger1140 Despite of what is shown on the dock, the actual title of the window does not contain Little Arc on it, so matching with regex won't work.

**Comment by diegoquinteiro** [comment]
+1 @mpeterson, that'd be a great feature

**Comment by ianyh** [comment]
You can check to see if Amethyst knows about a title with the cli debug tools.
```bash
/Applications/Amethyst.app/Contents/MacOS/Amethyst debug windows
```
But adding other sources of floating logic seems reasonable, generally speaking, but the UI gets more complicated.

**Comment by heyvito** [comment]
> You can check to see if Amethyst knows about a title with the cli debug tools.

```
Arc (pid 17496)
        Title:
        Frame: (1130.0, 719.0, 916.0, 515.0)
        id: 18215
        ScreenID: 37D8832A-2D66-02CA-B9F7-8F30A301B230
        Screen Frame: (0.0, 0.0, 2056.0, 1329.0)
        isActive: true
        isOnScreen: true
        isFocused: false
        shouldBeManaged: false
        shouldFloat: false

        Title: heyvito/dotfiles: 💻 @heyvito's dotfiles
        Frame: (130.0, 64.0, 1028.0, 1160.0)
        id: 18294
        ScreenID: 37D8832A-2D66-02CA-B9F7-8F30A301B230
        Screen Frame: (0.0, 0.0, 2056.0, 1329.0)
        isActive: true
        isOnScreen: true
        isFocused: false
        shouldBeManaged: true
        shouldFloat: false
```

The second window is actually Little Arc.

What if we could control floating windows by leveraging prefixes such as `identifier:`, `regex:`, etc? Or even just allow selection with a dropdown with options like `Identifier`, `Window Title`, and `Bundle ID`, defaulting to the last one.

@ianyh I could give this a try and open a PR if you think that would add any value to your project! :)
