### ISSUE TITLE
amethyst.yml isn't loading shortcuts

### ISSUE THREAD

**Issue by bjornevik** [ianyh/Amethyst#1726]
**Describe the bug**
After upgrading to 22.1 the shortcuts I have defined in my `xgd_config/amethyst/amethyst.yml`-file no longer seem to be loaded on startup. I have to manually open preferences and add the shortcuts I need.

The layouts and floating windows do seem to be loaded correctly.

**Applications:**
Amethyst.

**To Reproduce**
Open amethyst with self-defined shortcuts in an `amethyst.yml`-file. I also personally had problems with shortcuts not being loaded even when deleting `amethyst.yml`

**Expected behavior**
For the defined shortcuts to be loaded.

**Screenshots**
My `amethyst.yml`:
```yml
# set up layouts
layouts:
  - tall-right
  - floating
  - middle-wide
  - fullscreen

floating-is-blacklist: true

floating:
  - "com.apple.systempreferences"
  - "com.apple.iphonesimulator"
  - "com.bitwarden.desktop"
  - "com.insomnia.app"
  - "com.apple.finder"
  - "com.apple.AppStore"
  - "com.apple.ActivityMonitor"
  - "com.facebook.sonar"
  - "com.microsoft.VSCode"
  - "pl.maketheweb.cleanshotx"
  - "com.electron.firefoo"
  - "com.usebruno.app"
  - "com.google.android.studio"

window-margins: true
window-margin-size: 5
enables-layout-hud-on-space-change: false
focus-follows-mouse: 0
mouse-follows-focus: 1

# mod1: hyper
mod1:
  - option
  - shift
  - control
  - command

# mod2: meh
mod2:
  - option
  - shift
  - control

relaunch-amethyst:
  mod: mod2
  key: z

cycle-layout:
  mod: mod2
  key: r

select-fullscreen-layout:
  key: none

# defaults to need to unbind to not interfere with toggle-float
toggle-tiling: 
  key: none

toggle-float:
  mod: mod2
  key: t

swap-ccw:
  mod: mod2
  key: j

swap-cw:
  mod: mod2
  key: k

focus-ccw:
  mod: mod1
  key: j

focus-cw:
  mod: mod1
  key: k

shrink-main:
  mod: mod2
  key: h

expand-main:
  mod: mod2
  key: l

throw-space-left:
  mod: mod2
  key: "left"

throw-space-right:
  mod: mod2
  key: "right"

throw-space-1:
  mod: mod2
  key: 1

throw-space-2:
  mod: mod2
  key: 2

throw-space-3:
  mod: mod2
  key: 3

throw-space-4:
  mod: mod2
  key: 4

throw-space-5:
  mod: mod2
  key: 5

throw-space-6:
  mod: mod2
  key: 6

throw-space-7:
  mod: mod2
  key: 7

throw-space-8:
  mod: mod2
  key: 8

throw-space-9:
  mod: mod2
  key: 9
```

**Versions:**
 - macOS: Sequoia 15.2
 - Amethyst: 22.1
 
**Debug Info**
```
❯ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
Version: 0.22.1 (120)

OS version: Version 15.2 (Build 24C101)

Screens:
        (0.0, 0.0, 3840.0, 1200.0) [(0.0, 0.0, 3840.0, 1200.0)]

Configuration:
screen-padding-top: 0
mouse-follows-focus: 1
window-resize-step: 5
focus-follows-mouse: 0
window-minimum-height: 0
restore-layouts-on-launch: 1
use-canary-build: 0
window-minimum-width: 0
mod1: (
    option,
    shift,
    control,
    command
)
mod2: (
    option,
    shift,
    control
)
hide-menu-bar-icon: 0
enables-layout-hud-on-space-change: 0
enables-layout-hud: 1
window-margin-size: 5
window-max-count: 0
ignore-menu-bar: 0
follow-space-thrown-windows: 1
screen-padding-right: 0
mouse-resizes-windows: 0
new-windows-to-main: 0
screen-padding-left: 0
screen-padding-bottom: 0
mouse-swaps-windows: 0
window-margins: 1
floating-is-blacklist: 1
float-small-windows: 1
smart-window-margins: 0
floating: (
    "com.apple.systempreferences",
    "com.apple.iphonesimulator",
    "com.bitwarden.desktop",
    "com.insomnia.app",
    "com.apple.finder",
    "com.apple.AppStore",
    "com.apple.ActivityMonitor",
    "com.facebook.sonar",
    "com.microsoft.VSCode",
    "pl.maketheweb.cleanshotx",
    "com.electron.firefoo",
    "com.usebruno.app",
    "com.google.android.studio"
)
debug-layout-info: 0
disable-padding-on-builtin-display: 0
layouts: (
    "tall-right",
    floating,
    "middle-wide",
    fullscreen
)
```

**Additional context**
